Acme\DemoBundle\Entity\TraceMobiles:
    type: entity
    table: trace_mobiles
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        deviceId:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
            column: device_id
        time:
            type: datetime
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
